version: '3.3'
services:
    api:
        build: '/student-list/simple_api/'
        container_name: student-list_api
        network_mode: study-net
        ports:
            - '5000:5000'
        env_file:
            - .env_prod
        volumes:
            - '/student-list/simple_api/student_age.py:/data/student_age.py'
            - '/student-list/simple_api/student_age.json:/data/student_age.json'
    web:
        container_name: student-list_web
        network_mode: study-net
        ports:
            - '8080:80'
        env_file:
            - .env_prod
        volumes:
            - '/website:/var/www/html/'
        image: 'php:apache'
        depends_on:
            - 'api'
networks:
    study-net: