# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "regdocker" do |regdocker|
    regdocker.vm.box = "geerlingguy/centos7"
    regdocker.vm.network "private_network", type: "dhcp"
    regdocker.vm.hostname = "regdocker"
    regdocker.vm.provider "virtualbox" do |v|
      v.name = "regdocker"
      v.memory = 2048
      v.cpus = 2
    end
    regdocker.vm.provision :shell do |shell|
      shell.path = "install_regdocker.sh"
    end
  end
end
