# -*- mode: ruby -*-
# vi: set ft=ruby :

RAM = 4096
CPU = 4
IP = "10.0.0.201"

# Check Vagrant plugins
# If you want to ensure that vagrant-winnfsd is installed and enabled every time you run your vagrant box, just add the following to your vagrant file, just before the code block
if Vagrant::Util::Platform.windows? then
  unless Vagrant.has_plugin?("vagrant-winnfsd")
    raise  Vagrant::Errors::VagrantError.new, "vagrant-winnfsd plugin is missing. Please install it using 'vagrant plugin install vagrant-winnfsd' and rerun 'vagrant up'"
  end
end
# If you want to ensure that vagrant-vbguest is installed and enabled every time you run your vagrant box, just add the following to your vagrant file, just before the code block
if Vagrant::Util::Platform.windows? then
  unless Vagrant.has_plugin?("vagrant-vbguest")
    raise  Vagrant::Errors::VagrantError.new, "vagrant-vbguest plugin is missing. Please install it using 'vagrant plugin install vagrant-vbguest' and rerun 'vagrant up'"
  end
end
# If you want to ensure that vagrant-share is installed and enabled every time you run your vagrant box, just add the following to your vagrant file, just before the code block
if Vagrant::Util::Platform.windows? then
  unless Vagrant.has_plugin?("vagrant-share")
    raise  Vagrant::Errors::VagrantError.new, "vagrant-share plugin is missing. Please install it using 'vagrant plugin install vagrant-share' and rerun 'vagrant up'"
  end
end

Vagrant.configure("2") do |config|
  config.vm.define "regdocker" do |regdocker|
    regdocker.vm.box = "ubuntu/xenial64"
    regdocker.vm.network "private_network", ip: IP
	  regdocker.vm.hostname = "regdocker"
    regdocker.vm.provider "virtualbox" do |v|
  	  v.name = "regdocker"
  	  v.memory = RAM
  	  v.cpus = CPU
  	end
  	regdocker.vm.provision :shell do |shell|
  	  shell.path = "install_docker.sh"
    end 
  end
end
