# -*- mode: ruby -*-
# vi: set ft=ruby :

RAM = 4096
CPU = 4
IP = "10.0.0.201"

# Check Vagrant plugins
# If you want to ensure that vagrant-winnfsd is installed and enabled every time you run your vagrant box, just add the following to your vagrant file, just before the code block
if Vagrant::Util::Platform.windows? then
  unless Vagrant.has_plugin?("vagrant-winnfsd")
    raise  Vagrant::Errors::VagrantError.new, "vagrant-winnfsd plugin is missing. Please install it using 'vagrant plugin install vagrant-winnfsd' and rerun 'vagrant up'"
  end
end
# If you want to ensure that vagrant-vbguest is installed and enabled every time you run your vagrant box, just add the following to your vagrant file, just before the code block
if Vagrant::Util::Platform.windows? then
  unless Vagrant.has_plugin?("vagrant-vbguest")
    raise  Vagrant::Errors::VagrantError.new, "vagrant-vbguest plugin is missing. Please install it using 'vagrant plugin install vagrant-vbguest' and rerun 'vagrant up'"
  end
end
# If you want to ensure that vagrant-share is installed and enabled every time you run your vagrant box, just add the following to your vagrant file, just before the code block
if Vagrant::Util::Platform.windows? then
  unless Vagrant.has_plugin?("vagrant-share")
    raise  Vagrant::Errors::VagrantError.new, "vagrant-share plugin is missing. Please install it using 'vagrant plugin install vagrant-share' and rerun 'vagrant up'"
  end
end
# SCRIPT for provisioning the magic system :)
$install_docker_script = <<SCRIPT
echo Installing Docker Registry...
echo "Preparing node..."
# Install dependent packages
yum install -y yum-utils device-mapper-persistent-data lvm2 epel-release httpd-tools tree telnet
# Setup docker repository
yum-config-manager \
    --add-repo \
    https://download.docker.com/linux/centos/docker-ce.repo
# Update Yum cache
yum makecache fast
# Install docker
yum install -y docker-ce
# Install python-pip
yum install -y python-pip
# Install docker-compose
pip install docker-compose
# Start & enable docker
systemctl start docker
systemctl enable docker
# Verify docker installation
docker run --rm hello-world
# Copy docker-registry.service into systemd
cp /vagrant/registry/files/docker-registry.service /etc/systemd/system/
# Enable and start docker-registry service
systemctl enable docker-registry.service
service docker-registry start
SCRIPT

# The vagrant config for virtual machine named regdocker
Vagrant.configure('2') do |config|
  config.vm.define :regdocker, primary: true  do |regdocker|
    regdocker.vm.box = 'geerlingguy/centos7'
    regdocker.vbguest.auto_update = false
    regdocker.vm.network :private_network, ip: IP
    regdocker.vm.hostname = "regdocker"
    regdocker.vm.synced_folder ".", "/vagrant"
    regdocker.vm.provision "shell", inline: $install_docker_script, privileged: true
    regdocker.vm.provider "virtualbox" do |vb|
      vb.name = "regdocker"
      vb.memory = RAM
  	  vb.cpus = CPU
    end
  end
end
